build:
  image: default-jammy
  environment:
    php:
      version: 8.4
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
filter:
  excluded_paths:
    - '.github/*'
    - 'tests/*'
checks:
  php:
    parse_doc_comments: false
    verify_property_names: false
    verify_access_scope_valid: false
    property_assignments: false
    method_calls_on_non_object: false
    argument_type_checks: false
