name: PHPArkitect

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.4' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            files:
              - '.github/ci/phparkitect/*'
              - '.github/workflows/phparkitect.yml'
              - 'bin/valkyrja'
              - 'functions/*.php'
              - 'src/*.php'
              - 'tests/*.php'
              - 'composer.json'

      - name: Setup PHP
        if: steps.changes.outputs.files == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl

      - name: Install Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install PHPArkitect Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/phparkitect

      - name: Run PHPArkitect
        if: steps.changes.outputs.files == 'true'
        run: |
          composer phparkitect
