name: PHP CS Fixer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    permissions:
      # Required for commenting on pull requests
      pull-requests: write

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        php: [ '8.4' ]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Determine if workflow should run based on files changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            files:
              - '.github/ci/phpcsfixer/**'
              - '.github/workflows/phpcsfixer.yml'
              - 'bin/valkyrja'
              - 'functions/**/*.php'
              - 'src/**/*.php'
              - 'tests/**/*.php'
              - 'composer.json'

      - name: Setup PHP
        if: steps.changes.outputs.files == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl

      - name: Install Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install PHP CS Fixer Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/phpcsfixer

      - name: Run PHP CS Fixer
        if: steps.changes.outputs.files == 'true'
        run: |
          composer phpcsfixer-check

      - name: Report failure in PR comment
        # if: steps.build_step.outcome == 'failure'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          # Check if it's a pull request event
          if [ -z "$PR_URL" ]; then
            echo "Not a pull request, skipping comment."
            exit 0
          fi

          # Extract relevant failure info, e.g., last 50 lines of log
          # tail -n 50 build.log > build_tail.log

          # Post the comment using the GitHub CLI
          # The `gh pr comment` command requires the PR number or URL
          # --body-file build_tail.log
          gh pr comment "$PR_URL" --body "Please run `composer phpcsfixer-fix` locally and commit the changes"