name: PHPUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        # os: [ 'ubuntu-latest', 'windows-latest' ]
        php: [ '8.4', '8.5', '8.6' ]

    name: PHP ${{ matrix.php }} (${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'Windows'  }})

    continue-on-error: ${{ matrix.php == '8.6' }}

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sodium, fileinfo, pdo, php-mysql, php-sqlite3, php-pgsql, pdo_sqlite, pdo_pgsql, pdo_mysql xdebug
          ini-values: zend.assertions=1
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install PHPUnit Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/phpunit

      - name: Install Suggested Packages Composer dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/suggested

      - name: Make build logs dir
        run: mkdir -p .github/ci/phpunit/build/logs

      - name: Run PHPUnit tests with no coverage
        if: ${{ matrix.php != '8.4' }}
        run: |
          composer phpunit-no-cov

      - name: Run PHPUnit tests with full coverage
        if: ${{ matrix.php == '8.4' }}
        run: |
          composer phpunit-coverage

      - name: Upload Coveralls coverage report
        uses: coverallsapp/github-action@v2.3.6
        if: ${{ matrix.php == '8.4' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ".github/ci/phpunit/build/logs/clover.xml"
          format: "clover"
