name: PHPUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  # Required for commenting on pull requests
  pull-requests: write
  contents: read

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ 'ubuntu-latest' ]
        # os: [ 'ubuntu-latest', 'windows-latest' ]
        php: [ '8.4', '8.5', '8.6' ]

    name: PHP ${{ matrix.php }} (${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'Windows'  }})

    runs-on: ${{ matrix.os }}

    continue-on-error: ${{ matrix.php == '8.6' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Determine if workflow should run based on files changed
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            files:
              - '.github/ci/phpunit/**'
              - '.github/ci/suggested/**'
              - '.github/workflows/phpunit.yml'
              - 'bin/valkyrja'
              - 'functions/**/*.php'
              - 'src/**/*.php'
              - 'tests/**/*.php'
              - 'composer.json'

      - name: Setup PHP
        if: steps.changes.outputs.files == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, sodium, fileinfo, pdo, php-mysql, php-sqlite3, php-pgsql, pdo_sqlite, pdo_pgsql, pdo_mysql xdebug
          ini-values: zend.assertions=1

      - name: Install Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")

      - name: Install PHPUnit Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/phpunit

      - name: Install Suggested Packages Composer dependencies
        if: steps.changes.outputs.files == 'true'
        uses: ramsey/composer-install@v3
        with:
          composer-options: ${{ matrix.php == '8.6' && '--ignore-platform-req=php+' || '' }} --prefer-dist --no-progress
          custom-cache-suffix: $(date -u "+%Y-%m")
          working-directory: .github/ci/suggested

      - name: Make build logs dir
        if: steps.changes.outputs.files == 'true'
        run: mkdir -p .github/ci/phpunit/build/logs

      - name: Run PHPUnit tests with no coverage
        if: ${{ matrix.php != '8.4' && steps.changes.outputs.files == 'true' }}
        run: |
          composer phpunit-no-cov

      - name: Run PHPUnit tests with full coverage
        if: ${{ matrix.php == '8.4' && steps.changes.outputs.files == 'true' }}
        run: |
          composer phpunit-coverage

      - name: Upload Coveralls coverage report
        uses: coverallsapp/github-action@v2.3.6
        if: ${{ matrix.php == '8.4' && steps.changes.outputs.files == 'true' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ".github/ci/phpunit/build/logs/clover.xml"
          format: "clover"

      - name: Report failure in PR comment
        if: steps.build_step.outcome == 'failure'
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          OS: ${{ matrix.os == 'ubuntu-latest' && 'Linux' || 'Windows' }}
          PHP_VERSION: ${{ matrix.php }}
        run: |
          # Check if it's a pull request event
          if [ -z "$PR_URL" ]; then
            echo "Not a pull request, skipping comment."
            exit 0
          fi

          gh pr comment "$PR_URL" --body "PHPUnit failed for PHP $PHP_VERSION on $OS. Please run \`composer phpunit\` locally, fix all the issues, and commit the changes."
