name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

run-name: Release ${{ inputs.version }}

permissions:
  contents: write

jobs:
  check-version:
    name: Validate Release Version

    runs-on: ubuntu-latest

    steps:
      - name: Validate Format
        env:
          VERSION: ${{ inputs.version }}
        run: |
          # Update this when new major releases are made (25|26) for example.
          # Format is (MINIMUM_MAJOR_VERSION_SUPPORTED|CURRENT_MAJOR_VERSION_SUPPORTED)
          if [[ $VERSION =~ ^v(25).([0-9]+).([0-9]+)$ ]]; then
            echo "Valid version"
          else
            echo "Invalid version passed"

            exit 1
          fi

  check-composer:
    needs: check-version

    strategy:
      matrix:
        paths:
          - name: Root
            path: ./
          - name: Churn
            path: .github/ci/churn
          - name: PHPArkitect
            path: .github/ci/phparkitect
          - name: PHP Code Sniffer
            path: .github/ci/phpcodesniffer
          - name: PHP CS Fixer
            path: .github/ci/phpcsfixer
          - name: PHP Metrics
            path: .github/ci/phpmetrics
          - name: PHPStan
            path: .github/ci/phparkitect
          - name: PHPUnit
            path: .github/ci/phpunit
          - name: Psalm
            path: .github/ci/psalm
          - name: Rector
            path: .github/ci/rector
          - name: Suggested Packages
            path: .github/ci/suggested

    name: "Check ${{ matrix.paths.name }} Composer For Updates"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl

      - name: Check Composer For Updates
        env:
          COMPOSER_NAME: ${{ matrix.paths.name }}
          COMPOSER_PATH: ${{ matrix.paths.path }}
        run: |
          cd $COMPOSER_PATH

          COMPOSER=$(composer update 2>&1)
          NO_CHANGES_TEXT="Nothing to install, update or remove"

          if echo "$COMPOSER" | grep -q "$NO_CHANGES_TEXT"; then
            echo "$COMPOSER_NAME Composer packages are up to date"

            exit 0
          else
            echo "$COMPOSER_NAME Composer packages need to be updated"

            # Display the results so we can see what may need to be updated
            echo "$COMPOSER"
          
            exit 1
          fi

  release:
    needs: check-composer

    name: Release ${{ inputs.version }}

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      notes: ${{ steps.cleaned-notes.outputs.notes }}

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.VALKYRJA_GHA_APP_ID }}
          private-key: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Remove optional "v" prefix
        id: version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          echo "version=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Get all tags for repository
        id: get_tags
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: GET /repos/${{ github.repository }}/git/matching-refs/tags

      - name: Check if version already exists
        id: version-guard
        env:
          VERSION: v${{ steps.version.outputs.version }}
          TAGS: ${{ steps.get_tags.outputs.data }}
        run: |
          if [[ $TAGS == *"refs/tags/$VERSION"* ]]; then
            echo "Version exists! Aborting."

            exit 1
          else
            echo "Version does not exist! Proceeding."
          fi

      - name: Check if branch and version match
        if: ${{ github.ref_name != 'main' && github.ref_name != 'master' }}
        id: guard
        env:
          BRANCH: ${{ github.ref_name }}
          NUMERIC_VERSION: ${{ steps.version.outputs.version }}
        run: |
          MAJOR_VERSION="${NUMERIC_VERSION%%.*}"
          BRANCH_MAJOR_VERSION="${BRANCH%%.*}"

          if [ "$MAJOR_VERSION" != "$BRANCH_MAJOR_VERSION" ]; then
            echo "Mismatched versions! Aborting."
          
            exit 1
          else
            echo "Versions match! Proceeding."
          fi

      - name: Update Application.php version
        run: sed -i "s/const string VERSION = '.*';/const string VERSION = '${{ steps.version.outputs.version }}';/g" src/Valkyrja/Application/Contract/Application.php

      - name: Update VERSION.md version
        run: sed -i "s/.*/${{ steps.version.outputs.version }}/g" VERSION.md

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Release] Update version for v${{ steps.version.outputs.version }} release"

      - name: Generate release notes
        id: generated-notes
        uses: RedCrafter07/release-notes-action@main
        with:
          tag-name: v${{ steps.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Cleanup release notes
        id: cleaned-notes
        env:
          RELEASE_NOTES: ${{ steps.generated-notes.outputs.release-notes }}
        run: |
          START_FROM=$(echo -n "$RELEASE_NOTES" | awk "/What's Changed/{ print NR; exit }" -)
          DROP_FROM_CONTRIBUTORS=$(echo -n "$RELEASE_NOTES" | awk "/New Contributors/{ print NR; exit }" -)
          DROP_FROM_FULL_CHANGELOG=$(echo -n "$RELEASE_NOTES" | awk "/Full Changelog/{ print NR; exit }" -)

          # Drop everything starting from "Full Changelog"
          if [ ! -z "$DROP_FROM_FULL_CHANGELOG" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${DROP_FROM_FULL_CHANGELOG},$ d")
          fi

          # Drop everything starting from "New Contributors"
          if [ ! -z "$DROP_FROM_CONTRIBUTORS" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${DROP_FROM_CONTRIBUTORS},$ d")
          fi

          # Drop the line "What's Changed"
          if [ ! -z "$START_FROM" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${START_FROM}d")
          fi

          {
            echo 'notes<<EOF'
            echo "$RELEASE_NOTES"
            echo EOF
          } >> "$GITHUB_OUTPUT";

      - name: Get date for release
        id: release_date
        run: |
          # Convert timestamp to MST date in Y-m-d format
          FORMATED_DATE=$(TZ='America/Phoenix' date +%Y-%m-%d)

          # Make date available to other steps
          echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          # Pass extracted release date, release notes and version to the Action.
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ steps.cleaned-notes.outputs.notes }}
          latest-version: v${{ steps.version.outputs.version }}
          compare-url-target-revision: ${{ github.ref_name }}
          parse-github-usernames: true

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          # Push updated CHANGELOG to release target branch.
          branch: ${{ github.ref_name }}
          commit_message: "[Release] Update CHANGELOG for v${{ steps.version.outputs.version }} release"
          file_pattern: CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          body: ${{ steps.generated-notes.outputs.release-notes }}
          target_commitish: ${{ github.ref_name }}
          make_latest: "${{ github.ref_name == github.event.repository.default_branch }}"
