name: Create a New Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

run-name: Release ${{ inputs.version }}

permissions:
  contents: write

jobs:
  check-version:
    name: Validate Release Version

    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version.outputs.version }}
      major-version: ${{ steps.major-version.outputs.version }}

    steps:
      - name: Validate Format
        env:
          VERSION: ${{ inputs.version }}
        run: |
          # Update this when new major releases are made (25|26) for example.
          # Format is (MINIMUM_MAJOR_VERSION_SUPPORTED|CURRENT_MAJOR_VERSION_SUPPORTED)
          if [[ $VERSION =~ ^v(25).([0-9]+).([0-9]+)$ ]]; then
            echo "Valid version"
          else
            echo "Invalid version passed"

            exit 1
          fi

      - name: Remove "v" prefix
        id: version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          echo "version=${VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Get major version number
        id: major-version
        env:
          NUMERIC_VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "version=${NUMERIC_VERSION%%.*}" >> "$GITHUB_OUTPUT"

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.VALKYRJA_GHA_APP_ID }}
          private-key: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Get all tags for repository
        id: get_tags
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: GET /repos/${{ github.repository }}/git/matching-refs/tags

      - name: Check if version already exists
        id: version-guard
        env:
          VERSION: v${{ steps.version.outputs.version }}
          TAGS: ${{ steps.get_tags.outputs.data }}
        run: |
          if [[ $TAGS == *"refs/tags/$VERSION"* ]]; then
            echo "Version exists! Aborting."

            exit 1
          else
            echo "Version does not exist! Proceeding."
          fi

      - name: Check if branch and version match
        if: ${{ github.ref_name != 'main' && github.ref_name != 'master' }}
        id: guard
        env:
          BRANCH: ${{ github.ref_name }}
          NUMERIC_VERSION: ${{ steps.version.outputs.version }}
          MAJOR_VERSION: ${{ steps.major-version.outputs.version }}
        run: |
          BRANCH_MAJOR_VERSION="${BRANCH%%.*}"

          echo "Release major version: $MAJOR_VERSION"
          echo "Branch major version: $BRANCH_MAJOR_VERSION"

          if [ "$MAJOR_VERSION" != "$BRANCH_MAJOR_VERSION" ]; then
            echo "Mismatched versions! Aborting."
          
            exit 1
          else
            echo "Versions match! Proceeding."
          fi

  check-composer:
    needs: check-version

    strategy:
      matrix:
        paths:
          - name: Root
            command: root-outdated-check
          - name: Churn
            command: churn-outdated-check
          - name: PHPArkitect
            command: phparkitect-outdated-check
          - name: PHP Code Sniffer
            command: phpcodesniffer-outdated-check
          - name: PHP CS Fixer
            command: phpcsfixer-outdated-check
          - name: PHP Metrics
            command: phpmetrics-outdated-check
          - name: PHPStan
            command: phparkitect-outdated-check
          - name: PHPUnit
            command: phpunit-outdated-check
          - name: Psalm
            command: psalm-outdated-check
          - name: Rector
            command: rector-outdated-check
          - name: Suggested Packages
            command: suggested-outdated-check

    name: "Check ${{ matrix.paths.name }} Composer For Outdated Direct Dependencies"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl

      - name: Check Composer For Updates
        env:
          COMPOSER_NAME: ${{ matrix.paths.name }}
          COMPOSER_COMMAND: ${{ matrix.paths.command }}
        run: |
          output=$(eval "composer ${COMPOSER_COMMAND}" 2>&1)
          if [[ "$output" == *"All your direct dependencies are up to date"* ]]; then
            echo "$output"
            echo "Proceeding..."

            exit 0
          else
            echo "Composer dependencies must be updated before releasing. People rely on us to be on latest"
            echo "$output"

            exit 1
          fi

  release:
    needs: [ check-composer, check-version ]

    name: Release ${{ inputs.version }}

    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.VALKYRJA_GHA_APP_ID }}
          private-key: ${{ secrets.VALKYRJA_GHA_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Get date for build
        id: build_date
        run: |
          # Convert timestamp to MST date in Y-m-d format
          FORMATED_DATE=$(TZ='America/Phoenix' date '+%B %-d %Y %T MST')

          # Make date available to other steps
          echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

      - name: Update Application.php version
        run: |
          sed -i "s/const string VERSION = '.*';/const string VERSION = '${{ needs.check-version.outputs.version }}';/g" src/Valkyrja/Application/Kernel/Contract/ApplicationContract.php
          sed -i "s/const string VERSION_BUILD_DATE_TIME = '.*';/const string VERSION_BUILD_DATE_TIME = '${{ steps.build_date.outputs.date }}';/g" src/Valkyrja/Application/Kernel/Contract/ApplicationContract.php

      - name: Update VERSION.md version
        run: |
          sed -i "s/.*/${{ needs.check-version.outputs.version }}/g" VERSION.md

      - name: Commit version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[Release] Update version for ${{ inputs.version }} release"

      - name: Generate release notes
        id: generated-notes
        uses: RedCrafter07/release-notes-action@main
        with:
          tag-name: ${{ inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}

      - name: Cleanup release notes
        id: cleaned-notes
        env:
          RELEASE_NOTES: ${{ steps.generated-notes.outputs.release-notes }}
        run: |
          START_FROM=$(echo -n "$RELEASE_NOTES" | awk "/What's Changed/{ print NR; exit }" -)
          DROP_FROM_CONTRIBUTORS=$(echo -n "$RELEASE_NOTES" | awk "/New Contributors/{ print NR; exit }" -)
          DROP_FROM_FULL_CHANGELOG=$(echo -n "$RELEASE_NOTES" | awk "/Full Changelog/{ print NR; exit }" -)

          # Drop everything starting from "Full Changelog"
          if [ ! -z "$DROP_FROM_FULL_CHANGELOG" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${DROP_FROM_FULL_CHANGELOG},$ d")
          fi

          # Drop everything starting from "New Contributors"
          if [ ! -z "$DROP_FROM_CONTRIBUTORS" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${DROP_FROM_CONTRIBUTORS},$ d")
          fi

          # Drop the line "What's Changed"
          if [ ! -z "$START_FROM" ]; then
              RELEASE_NOTES=$(echo -n "$RELEASE_NOTES" | sed "${START_FROM}d")
          fi

          {
            echo 'notes<<EOF'
            echo "$RELEASE_NOTES"
            echo EOF
          } >> "$GITHUB_OUTPUT";

      - name: Get date for release
        id: release_date
        run: |
          # Convert timestamp to MST date in Y-m-d format
          FORMATED_DATE=$(TZ='America/Phoenix' date +%Y-%m-%d)

          # Make date available to other steps
          echo "date=$(echo $FORMATED_DATE)" >> $GITHUB_OUTPUT;

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          # Pass extracted release date, release notes and version to the Action.
          release-date: ${{ steps.release_date.outputs.date }}
          release-notes: ${{ steps.cleaned-notes.outputs.notes }}
          latest-version: ${{ inputs.version }}
          compare-url-target-revision: ${{ github.ref_name }}
          parse-github-usernames: true

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          # Push updated CHANGELOG to release target branch.
          branch: ${{ github.ref_name }}
          commit_message: "[Release] Update CHANGELOG for ${{ inputs.version }} release"
          file_pattern: CHANGELOG.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.version }}
          body: ${{ steps.generated-notes.outputs.release-notes }}
          target_commitish: ${{ github.ref_name }}
          make_latest: "${{ github.ref_name == github.event.repository.default_branch }}"
